# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-29 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Errors',
            fields=[
                ('error_id', models.CharField(default='Null', max_length=150, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('identifier', models.CharField(default='Null', max_length=150, primary_key=True, serialize=False)),
                ('full_name', models.TextField(default='Null')),
                ('owner', models.TextField(default='Null')),
                ('name', models.TextField(default='Null')),
                ('description', models.TextField(default='Null')),
                ('html_url', models.URLField(default='Null', max_length=350)),
            ],
        ),
    ]
