# Generated by Django 3.1.3 on 2020-11-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='fork_url',
            field=models.URLField(default='Null', max_length=350),
        ),
    ]
