# Generated by Django 3.1.3 on 2020-11-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzerapp', '0003_repository_api_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='fork_api_url',
            field=models.URLField(default='Null', max_length=350),
        ),
    ]
