# Generated by Django 3.1.3 on 2021-05-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzerapp', '0005_repository_default_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='pull_url',
            field=models.URLField(default='Null', max_length=350),
        ),
    ]
